# FunCommands for Craftbukkit / Spigot
# Author: Brandon (ThirtyVirus) Calabrese
#
# YouTube:      https://www.youtube.com/channel/UC04QdEl71CFDogk8pzY7Geg
# Twitter:      https://twitter.com/Thirtyvirus
# SpigotMC:     https://www.spigotmc.org/members/thirtyvirus.179587/

# Plugin Prefix
plugin-prefix: "&6[FUN] &7"